// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwpS2tQ84F0p1t43pyywfE7HkkcyVD6DQ',
    appId: '1:960362396159:web:1855daaa44ffe680b7cfca',
    messagingSenderId: '960362396159',
    projectId: 'flutter-notifi-882ff',
    authDomain: 'flutter-notifi-882ff.firebaseapp.com',
    storageBucket: 'flutter-notifi-882ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuDO2Vft5hLjIxvsBzLxuLdAiLp6GK8sY',
    appId: '1:960362396159:android:ad1e1dc1b6fb52d0b7cfca',
    messagingSenderId: '960362396159',
    projectId: 'flutter-notifi-882ff',
    storageBucket: 'flutter-notifi-882ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1cMF62b39wPUO_akWgJhw3nJSfC61oAY',
    appId: '1:960362396159:ios:6dcaeb42d9331745b7cfca',
    messagingSenderId: '960362396159',
    projectId: 'flutter-notifi-882ff',
    storageBucket: 'flutter-notifi-882ff.appspot.com',
    iosBundleId: 'com.example.notification',
  );
}
